name: Dependency Review

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
    dependency-review:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout Repository'
              uses: actions/checkout@v4
            - name: 'Review Vulnerabilities and Licenses'
              uses: actions/dependency-review-action@v4
              with:
                # will fail on or higher than high severity
                fail-on-severity: high
                show-openssf-scorecard: false
                # SPDX Expression should catch any gpl license - spdx.dev/use/specifications
                deny-licenses: GPL-1.0-only, GPL-1.0-or-later, GPL-2.0-only, GPL-2.0-or-later, GPL-3.0-only, GPL-3.0-or-later, LGPL-2.1-only, LGPL-2.1-or-later, LGPL-3.0-only, LGPL-3.0-or-later, AGPL-3.0-only, AGPL-3.0-or-later
                comment-summary-in-pr: on-failure
                # warn-only: true
                allow-dependencies-licenses: 'pkg:github/github.com/Checkmarx/kics-github-action'