---
name: Publish to PyPI

on:
  push:
    tags:
      - v*.*

defaults:
  run:
    shell: bash

jobs:
  package-and-release:
    runs-on: "ubuntu-latest"

    permissions:
      # Needed to create a 'release' on the repo.
      contents: write
      # Needed to authenticate with 3M Packages.
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install python deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install build twine

      - name: Build package for dev
        run: python -m build .

      - name: Publish the package
        run: python -m twine upload --username "__token__" --password ${{ secrets.TWINE_TOKEN }} --verbose dist/*

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          artifacts: "./dist/*"
